// Code generated by protoc-gen-go. DO NOT EDIT.
// source: world.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Aircraft struct {
	CallSign             string   `protobuf:"bytes,1,opt,name=CallSign,proto3" json:"CallSign,omitempty"`
	Heading              float32  `protobuf:"fixed32,2,opt,name=Heading,proto3" json:"Heading,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Elevation            float32  `protobuf:"fixed32,5,opt,name=Elevation,proto3" json:"Elevation,omitempty"`
	Speed                float32  `protobuf:"fixed32,6,opt,name=Speed,proto3" json:"Speed,omitempty"`
	Frequency            float32  `protobuf:"fixed32,7,opt,name=Frequency,proto3" json:"Frequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Aircraft) Reset()         { *m = Aircraft{} }
func (m *Aircraft) String() string { return proto.CompactTextString(m) }
func (*Aircraft) ProtoMessage()    {}
func (*Aircraft) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{0}
}

func (m *Aircraft) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aircraft.Unmarshal(m, b)
}
func (m *Aircraft) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aircraft.Marshal(b, m, deterministic)
}
func (m *Aircraft) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aircraft.Merge(m, src)
}
func (m *Aircraft) XXX_Size() int {
	return xxx_messageInfo_Aircraft.Size(m)
}
func (m *Aircraft) XXX_DiscardUnknown() {
	xxx_messageInfo_Aircraft.DiscardUnknown(m)
}

var xxx_messageInfo_Aircraft proto.InternalMessageInfo

func (m *Aircraft) GetCallSign() string {
	if m != nil {
		return m.CallSign
	}
	return ""
}

func (m *Aircraft) GetHeading() float32 {
	if m != nil {
		return m.Heading
	}
	return 0
}

func (m *Aircraft) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Aircraft) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Aircraft) GetElevation() float32 {
	if m != nil {
		return m.Elevation
	}
	return 0
}

func (m *Aircraft) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Aircraft) GetFrequency() float32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type UpdateMessage struct {
	CallSign             string    `protobuf:"bytes,1,opt,name=CallSign,proto3" json:"CallSign,omitempty"`
	AircraftInfo         *Aircraft `protobuf:"bytes,2,opt,name=AircraftInfo,proto3" json:"AircraftInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateMessage) Reset()         { *m = UpdateMessage{} }
func (m *UpdateMessage) String() string { return proto.CompactTextString(m) }
func (*UpdateMessage) ProtoMessage()    {}
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{1}
}

func (m *UpdateMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMessage.Unmarshal(m, b)
}
func (m *UpdateMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMessage.Marshal(b, m, deterministic)
}
func (m *UpdateMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMessage.Merge(m, src)
}
func (m *UpdateMessage) XXX_Size() int {
	return xxx_messageInfo_UpdateMessage.Size(m)
}
func (m *UpdateMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMessage proto.InternalMessageInfo

func (m *UpdateMessage) GetCallSign() string {
	if m != nil {
		return m.CallSign
	}
	return ""
}

func (m *UpdateMessage) GetAircraftInfo() *Aircraft {
	if m != nil {
		return m.AircraftInfo
	}
	return nil
}

type RemoveMessage struct {
	CallSign             string   `protobuf:"bytes,1,opt,name=CallSign,proto3" json:"CallSign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveMessage) Reset()         { *m = RemoveMessage{} }
func (m *RemoveMessage) String() string { return proto.CompactTextString(m) }
func (*RemoveMessage) ProtoMessage()    {}
func (*RemoveMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{2}
}

func (m *RemoveMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveMessage.Unmarshal(m, b)
}
func (m *RemoveMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveMessage.Marshal(b, m, deterministic)
}
func (m *RemoveMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMessage.Merge(m, src)
}
func (m *RemoveMessage) XXX_Size() int {
	return xxx_messageInfo_RemoveMessage.Size(m)
}
func (m *RemoveMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMessage proto.InternalMessageInfo

func (m *RemoveMessage) GetCallSign() string {
	if m != nil {
		return m.CallSign
	}
	return ""
}

type Response struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MonitorMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorMessage) Reset()         { *m = MonitorMessage{} }
func (m *MonitorMessage) String() string { return proto.CompactTextString(m) }
func (*MonitorMessage) ProtoMessage()    {}
func (*MonitorMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b509c40833d40ff2, []int{4}
}

func (m *MonitorMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorMessage.Unmarshal(m, b)
}
func (m *MonitorMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorMessage.Marshal(b, m, deterministic)
}
func (m *MonitorMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorMessage.Merge(m, src)
}
func (m *MonitorMessage) XXX_Size() int {
	return xxx_messageInfo_MonitorMessage.Size(m)
}
func (m *MonitorMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorMessage.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorMessage proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Aircraft)(nil), "v1.Aircraft")
	proto.RegisterType((*UpdateMessage)(nil), "v1.UpdateMessage")
	proto.RegisterType((*RemoveMessage)(nil), "v1.RemoveMessage")
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*MonitorMessage)(nil), "v1.MonitorMessage")
}

func init() { proto.RegisterFile("world.proto", fileDescriptor_b509c40833d40ff2) }

var fileDescriptor_b509c40833d40ff2 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xdd, 0x4a, 0xc3, 0x30,
	0x14, 0xa6, 0xd3, 0x75, 0xdb, 0xd9, 0x26, 0x1a, 0x44, 0xc2, 0xf0, 0x62, 0xf4, 0x6a, 0x43, 0x1c,
	0xdb, 0x7c, 0x02, 0x11, 0x45, 0x61, 0xbb, 0xe9, 0x10, 0xaf, 0xbc, 0x88, 0xeb, 0x59, 0x09, 0xd4,
	0xa4, 0x26, 0x59, 0xc5, 0xe7, 0xf0, 0xb5, 0x7c, 0x28, 0x49, 0xd2, 0x56, 0xea, 0x85, 0x78, 0xf9,
	0xfd, 0x9c, 0x73, 0xbe, 0xaf, 0x0d, 0xf4, 0xdf, 0xa5, 0xca, 0x92, 0x59, 0xae, 0xa4, 0x91, 0xa4,
	0x55, 0x2c, 0xa2, 0xaf, 0x00, 0xba, 0xd7, 0x5c, 0x6d, 0x15, 0xdb, 0x19, 0x32, 0x82, 0xee, 0x0d,
	0xcb, 0xb2, 0x0d, 0x4f, 0x05, 0x0d, 0xc6, 0xc1, 0xa4, 0x17, 0xd7, 0x98, 0x50, 0xe8, 0xdc, 0x23,
	0x4b, 0xb8, 0x48, 0x69, 0x6b, 0x1c, 0x4c, 0x5a, 0x71, 0x05, 0xed, 0xd4, 0x8a, 0x19, 0x6e, 0xf6,
	0x09, 0xd2, 0x03, 0x27, 0xd5, 0x98, 0x9c, 0x43, 0x6f, 0x25, 0x45, 0xea, 0xc5, 0x43, 0x27, 0xfe,
	0x10, 0x56, 0xbd, 0xcd, 0xb0, 0x60, 0x86, 0x4b, 0x41, 0xdb, 0x5e, 0xad, 0x09, 0x72, 0x0a, 0xed,
	0x4d, 0x8e, 0x98, 0xd0, 0xd0, 0x29, 0x1e, 0xd8, 0x99, 0x3b, 0x85, 0x6f, 0x7b, 0x14, 0xdb, 0x0f,
	0xda, 0xf1, 0x33, 0x35, 0x11, 0x3d, 0xc3, 0xf0, 0x31, 0x4f, 0x98, 0xc1, 0x35, 0x6a, 0xcd, 0x52,
	0xfc, 0xb3, 0xd2, 0x1c, 0x06, 0x55, 0xf5, 0x07, 0xb1, 0x93, 0xae, 0x57, 0x7f, 0x39, 0x98, 0x15,
	0x8b, 0x59, 0xc5, 0xc7, 0x0d, 0x47, 0x74, 0x01, 0xc3, 0x18, 0x5f, 0x65, 0xf1, 0x9f, 0xf5, 0x51,
	0x04, 0xdd, 0x18, 0x75, 0x2e, 0x85, 0x46, 0x72, 0x06, 0xa1, 0x36, 0xcc, 0xec, 0x75, 0xe9, 0x2a,
	0x51, 0x74, 0x0c, 0x47, 0x6b, 0x29, 0xb8, 0x91, 0xaa, 0xdc, 0xb8, 0xfc, 0x0c, 0x60, 0xf0, 0x64,
	0x7f, 0xd2, 0x06, 0x55, 0xc1, 0xb7, 0x48, 0xa6, 0x10, 0xfa, 0x4a, 0xe4, 0xc4, 0x26, 0x6b, 0xd4,
	0x1b, 0xb9, 0xb0, 0xf5, 0x95, 0x29, 0x84, 0x3e, 0x9e, 0xb7, 0x36, 0xa2, 0xfe, 0xb2, 0x5e, 0x42,
	0xa7, 0x3c, 0x4c, 0x88, 0x15, 0x9a, 0x29, 0x46, 0x8d, 0x8f, 0x30, 0x0f, 0x5e, 0x42, 0xf7, 0x62,
	0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x90, 0x4f, 0xf7, 0x40, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorldServiceClient is the client API for WorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorldServiceClient interface {
	Update(ctx context.Context, in *UpdateMessage, opts ...grpc.CallOption) (*Response, error)
	Remove(ctx context.Context, in *RemoveMessage, opts ...grpc.CallOption) (*Response, error)
	Monitor(ctx context.Context, in *MonitorMessage, opts ...grpc.CallOption) (WorldService_MonitorClient, error)
}

type worldServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldServiceClient(cc grpc.ClientConnInterface) WorldServiceClient {
	return &worldServiceClient{cc}
}

func (c *worldServiceClient) Update(ctx context.Context, in *UpdateMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.WorldService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) Remove(ctx context.Context, in *RemoveMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/v1.WorldService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldServiceClient) Monitor(ctx context.Context, in *MonitorMessage, opts ...grpc.CallOption) (WorldService_MonitorClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WorldService_serviceDesc.Streams[0], "/v1.WorldService/Monitor", opts...)
	if err != nil {
		return nil, err
	}
	x := &worldServiceMonitorClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WorldService_MonitorClient interface {
	Recv() (*Aircraft, error)
	grpc.ClientStream
}

type worldServiceMonitorClient struct {
	grpc.ClientStream
}

func (x *worldServiceMonitorClient) Recv() (*Aircraft, error) {
	m := new(Aircraft)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorldServiceServer is the server API for WorldService service.
type WorldServiceServer interface {
	Update(context.Context, *UpdateMessage) (*Response, error)
	Remove(context.Context, *RemoveMessage) (*Response, error)
	Monitor(*MonitorMessage, WorldService_MonitorServer) error
}

// UnimplementedWorldServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorldServiceServer struct {
}

func (*UnimplementedWorldServiceServer) Update(ctx context.Context, req *UpdateMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedWorldServiceServer) Remove(ctx context.Context, req *RemoveMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}
func (*UnimplementedWorldServiceServer) Monitor(req *MonitorMessage, srv WorldService_MonitorServer) error {
	return status.Errorf(codes.Unimplemented, "method Monitor not implemented")
}

func RegisterWorldServiceServer(s *grpc.Server, srv WorldServiceServer) {
	s.RegisterService(&_WorldService_serviceDesc, srv)
}

func _WorldService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WorldService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).Update(ctx, req.(*UpdateMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.WorldService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServiceServer).Remove(ctx, req.(*RemoveMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldService_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorldServiceServer).Monitor(m, &worldServiceMonitorServer{stream})
}

type WorldService_MonitorServer interface {
	Send(*Aircraft) error
	grpc.ServerStream
}

type worldServiceMonitorServer struct {
	grpc.ServerStream
}

func (x *worldServiceMonitorServer) Send(m *Aircraft) error {
	return x.ServerStream.SendMsg(m)
}

var _WorldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.WorldService",
	HandlerType: (*WorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _WorldService_Update_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _WorldService_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _WorldService_Monitor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "world.proto",
}
